[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "LuminaDB"
description = "Easy to use SQLite wrapper"
authors = [
    {name = "Rimu Eirnarn", email = "rimuru720@proton.me"}
]
keywords = ["sqlite", "sqlite3"]
readme = "README.md"
requires-python = ">=3.11"
license = "BSD-3-Clause"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython"
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/RimuEirnarn/luminadb"
Documentation = "https://luminadb.rtfd.io"
Repository = "https://github.com/RimuEirnarn/luminadb.git"

[tool.setuptools]
zip-safe = true
packages = ["luminadb", "luminadb.models", "luminadb.workers"]

[project.optional-dependencies]
dev = ["pytest", "pylint", "black"]
docs = ['sphinx', 'myst_parser']
